Test

diff --git a/19.03/Dockerfile b/19.03/Dockerfile
--- a/19.03/Dockerfile
+++ b/19.03/Dockerfile
@@ -1,18 +1,18 @@
-FROM alpine:3.11
+FROM ubuntu:18.04
 
-RUN apk add --no-cache \
-		ca-certificates \
-# DOCKER_HOST=ssh://... -- https://github.com/docker/cli/pull/1014
-		openssh-client
+RUN apt update && apt -y upgrade
+
+RUN apt install -y ca-certificates openssh-client wget git
 
 # set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
 # - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
 # - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
 # - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf
-RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
+RUN echo 'hosts: files dns' > /etc/nsswitch.conf
 
 ENV DOCKER_CHANNEL stable
 ENV DOCKER_VERSION 19.03.8
+ENV DOCKER_COMPOSE_VERSION 1.25.4
 # TODO ENV DOCKER_SHA256
 # https://github.com/docker/docker-ce/blob/5b073ee2cf564edee5adca05eee574142f7627bb/components/packaging/static/hash_files !!
 # (no SHA file artifacts on download.docker.com yet as of 2017-06-07 though)
@@ -20,17 +20,12 @@ ENV DOCKER_VERSION 19.03.8
 RUN set -eux; \
 	\
 # this "case" statement is generated via "update.sh"
-	apkArch="$(apk --print-arch)"; \
-	case "$apkArch" in \
+	aptArch="$(uname -m)"; \
+	case "$aptArch" in \
 # amd64
 		x86_64) dockerArch='x86_64' ;; \
-# arm32v6
-		armhf) dockerArch='armel' ;; \
-# arm32v7
-		armv7) dockerArch='armhf' ;; \
-# arm64v8
-		aarch64) dockerArch='aarch64' ;; \
-		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+#		armv7l) dockerArch='armhf' ;; \
+		*) echo >&2 "error: unsupported architecture ($aptArch)"; exit 1 ;;\
 	esac; \
 	\
 	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${dockerArch}/docker-${DOCKER_VERSION}.tgz"; then \
@@ -44,9 +39,12 @@ RUN set -eux; \
 		--directory /usr/local/bin/ \
 	; \
 	rm docker.tgz; \
+        wget -O /usr/local/bin/docker-compose "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-Linux-${dockerArch}"; \
+        chmod +x /usr/local/bin/docker-compose; \
 	\
 	dockerd --version; \
-	docker --version
+	docker --version; \
+        docker-compose --version;
 
 COPY modprobe.sh /usr/local/bin/modprobe
 COPY docker-entrypoint.sh /usr/local/bin/
